# Generated by Django 4.2.6 on 2023-11-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analizys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(blank=True, max_length=200, null=True)),
                ('initiated', models.DateField(blank=True, null=True)),
                ('termination', models.DateField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
