# Generated by Django 4.2.6 on 2023-10-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventorey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(blank=True, max_length=200, null=True)),
                ('generationDate', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('model_id', models.CharField(blank=True, max_length=200, null=True)),
                ('archive', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
