# Generated by Django 4.2.6 on 2023-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infomationGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('documentName', models.CharField(blank=True, max_length=200, null=True)),
                ('documentAuthor', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('docType', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
