# Generated by Django 4.2.6 on 2023-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.CharField(blank=True, max_length=200, null=True)),
                ('sensor', models.CharField(blank=True, max_length=200, null=True)),
                ('option', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
