# Generated by Django 4.2.6 on 2023-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informationSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sel', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('ownerauthor', models.CharField(blank=True, max_length=200, null=True)),
                ('documentName', models.CharField(blank=True, max_length=200, null=True)),
                ('docType', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('netName', models.CharField(blank=True, max_length=200, null=True)),
                ('countryName', models.CharField(blank=True, max_length=200, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=200, null=True)),
                ('gmt', models.CharField(blank=True, max_length=200, null=True)),
                ('regioncity', models.CharField(blank=True, max_length=200, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('os', models.CharField(blank=True, max_length=200, null=True)),
                ('plataform', models.CharField(blank=True, max_length=200, null=True)),
                ('suite', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
