# Generated by Django 4.2.6 on 2023-11-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='android',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(blank=True, max_length=200, null=True)),
                ('ReportDate', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=200, null=True)),
                ('uniqueDeviceId', models.CharField(blank=True, max_length=200, null=True)),
                ('productName', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('maker', models.CharField(blank=True, max_length=200, null=True)),
                ('productCode', models.CharField(blank=True, max_length=200, null=True)),
                ('radioSerial', models.CharField(blank=True, max_length=200, null=True)),
                ('version_so', models.CharField(blank=True, max_length=200, null=True)),
                ('model_id', models.CharField(blank=True, max_length=200, null=True)),
                ('computerMD', models.CharField(blank=True, max_length=200, null=True)),
                ('conputerSHA', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueReportIdentifier', models.CharField(blank=True, max_length=200, null=True)),
                ('ReportDate', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=200, null=True)),
                ('uniqueCode', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceFamily', models.CharField(blank=True, max_length=200, null=True)),
                ('productName', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('version_so', models.CharField(blank=True, max_length=200, null=True)),
                ('modelNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('modelHardware', models.CharField(blank=True, max_length=200, null=True)),
                ('serialDataBase', models.CharField(blank=True, max_length=200, null=True)),
                ('imei', models.CharField(blank=True, max_length=200, null=True)),
                ('codeCountry', models.CharField(blank=True, max_length=200, null=True)),
                ('codeOperator', models.CharField(blank=True, max_length=200, null=True)),
                ('addressBluetoot', models.CharField(blank=True, max_length=200, null=True)),
                ('addressEthernet', models.CharField(blank=True, max_length=200, null=True)),
                ('addressWife', models.CharField(blank=True, max_length=200, null=True)),
                ('computerMD', models.CharField(blank=True, max_length=200, null=True)),
                ('conputerSHA', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
